(() => {
  const form = document.querySelector("#campaignForm"), list = document.querySelector("#campaignList"), summary = document.querySelector("#campaignSummary"), date = document.querySelector("#campaignDate");
  if (!form || !list || !summary) return;
  const defaults = [{id:"medical-camp",title:"Free Medical Check-up Camp",time:"08:30",location:"Kosi Kalan Community Hall, Mathura",volunteers:14,icon:"fa-kit-medical",type:"medical",status:"Happening today"},{id:"food-distribution",title:"Prasad & Food Distribution",time:"10:00",location:"Banke Bihari Mandir area, Vrindavan",volunteers:10,icon:"fa-bowl-food",type:"food-camp",status:"Scheduled"},{id:"education-drive",title:"Children's Education Drive",time:"13:30",location:"Chhata Village School, Mathura",volunteers:8,icon:"fa-book-open-reader",type:"education-camp",status:"Scheduled"},{id:"senior-support",title:"Senior Citizen Support Visit",time:"16:00",location:"Goverdhan Ashram, Goverdhan",volunteers:7,icon:"fa-hand-holding-heart",type:"support",status:"Scheduled"},{id:"yamuna-drive",title:"Clean Yamuna Awareness Drive",time:"17:30",location:"Keshi Ghat, Vrindavan",volunteers:8,icon:"fa-recycle",type:"clean",status:"Scheduled"}];
  let campaigns = App.read("nss.campaigns", defaults);
  const displayTime = value => new Intl.DateTimeFormat("en-IN",{hour:"2-digit",minute:"2-digit",hour12:true}).format(new Date(`2000-01-01T${value}`)).replace(" ","");
  const render = () => { const volunteerTotal = campaigns.reduce((total,item) => total + Number(item.volunteers || 0),0); summary.textContent = `${campaigns.length} campaign${campaigns.length === 1 ? "" : "s"} · ${volunteerTotal} volunteers scheduled`; list.innerHTML = campaigns.length ? campaigns.map(item => `<article class="campaign-card"><div class="campaign-time"><strong>${App.escapeHtml(displayTime(item.time))}</strong></div><div class="campaign-icon ${App.escapeHtml(item.type || "medical")}"><i class="fa-solid ${App.escapeHtml(item.icon || "fa-calendar-day")}"></i></div><div class="campaign-info"><span class="campaign-status ${item.status === "Happening today" ? "live" : ""}">${App.escapeHtml(item.status || "Scheduled")}</span><h2>${App.escapeHtml(item.title)}</h2><p><i class="fa-solid fa-location-dot"></i> ${App.escapeHtml(item.location)}</p></div><div class="campaign-team"><strong>${App.escapeHtml(item.volunteers)}</strong><span>volunteers</span></div><div class="campaign-actions"><a class="btn btn-success" href="volunteers.html">View team</a><button class="btn btn-danger" type="button" data-delete="${App.escapeHtml(item.id)}" aria-label="Delete ${App.escapeHtml(item.title)}"><i class="fa-solid fa-trash"></i> Delete</button></div></article>`).join("") : '<div class="campaign-empty">No campaigns scheduled. Add one above to get started.</div>'; };
  form.addEventListener("submit", event => { event.preventDefault(); if (!form.reportValidity()) return; campaigns.push({id:App.id(),title:form.campaignTitle.value.trim(),time:form.campaignTime.value,location:form.campaignLocation.value.trim(),volunteers:Number(form.campaignVolunteers.value),icon:"fa-calendar-day",type:"medical",status:"Scheduled"}); App.write("nss.campaigns",campaigns); form.reset(); render(); App.toast("Campaign added."); });
  list.addEventListener("click", event => { const button = event.target.closest("[data-delete]"); if (!button || !App.confirmDelete("campaign")) return; campaigns = campaigns.filter(item => item.id !== button.dataset.delete); App.write("nss.campaigns",campaigns); render(); App.toast("Campaign deleted."); });
  if (date) date.textContent = new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());
  render();
})();
